### ISSUE TITLE
Book

### ISSUE THREAD

**Issue by ghost** [nfisher23/learn-java-from-csharp-code#1]
I enjoy reading your book in kindle format. When is it available as PDF or Hardcopy?

**Comment by nfisher23** [comment]
Hey Eric, thanks! When I published the book to Amazon I made sure to keep it DRM-free. You should be able to convert the azw file directly into a pdf without any issue using something like Calibre (https://calibre-ebook.com/). You have my full permission to share it anywhere with anyone, as long as it is in its full and original form.

I also have a backlog item to publish the chapters to my website in its own section. Realistically, it could take until mid April or so before that's available, but I'll make a note to come back here and comment again when it is.

**Comment by ghost** [comment]
Thanks Nick! If you plan to publish a hardcopy please drop me a note.
